#! /usr/bin/env python2

import csv
import sys
import os

filename = sys.argv[1]
print "Processing", filename

interested_cols = ['Carrier', 'Origin', 'Dest',
        'DepDelayMinutes', 'ArrDelayMinutes', 'DepTime',
        'Year', 'Month', 'DayofMonth', 'DayOfWeek',
        'AirlineID']

basename = filename[:-4]
with open(filename) as fh:
    with open('%s.concise.csv' % basename, 'w') as target_fh:
        reader = csv.reader(fh)
        writer = csv.writer(target_fh)

        header = reader.next()
        interested_idx = [header.index(col) for col in interested_cols]

        #writer.writerow(interested_cols)
        for row in reader:
            row = [row[i] for i in interested_idx]
            writer.writerow(row)

os.remove(filename)
